[package]
name = "lightpack"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lightpack-derive = { version = "0.1.0", path = "derive" }
lightpack-shared = { version = "0.1.0", path = "shared" }
byteorder = { workspace = true }

[workspace]
members = [
    "derive",
    "shared"
]

[workspace.dependencies]
byteorder = "1"
